services:
  - type: web
    name: marketplace
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        fromDatabase:
          name: marketplace-db
          property: secretKey
      - key: USE_POSTGRES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace-db
          property: connectionString

databases:
  - name: marketplace-db
    plan: free
    version: 15
